CREATE TABLE BRANDS (
BRAND_ID INT NOT NULL,
BRAND_NAME VARCHAR,
PRIMARY KEY (BRAND_ID)
);

CREATE TABLE PRICES (
BRAND_ID INT,
START_DATE DATETIME,
END_DATE DATETIME,
PRICE_LIST INT,
PRODUCT_ID INT,
PRIORITY INT,
PRICE DECIMAL,
CURR VARCHAR,
FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID)
);