CREATE TABLE IF NOT EXISTS BRANDS (
BRAND_ID INT NOT NULL,
BRAND_NAME VARCHAR,
PRIMARY KEY (BRAND_ID)
);

CREATE TABLE IF NOT EXISTS PRICES (
ID INT NOT NULL AUTO_INCREMENT,
BRAND_ID INT,
START_DATE DATETIME,
END_DATE DATETIME,
PRICE_LIST INT,
PRODUCT_ID INT,
PRIORITY INT,
PRICE FLOAT,
CURR VARCHAR,
PRIMARY KEY (ID),
FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID)
);